### ISSUE TITLE
Error en variable

### ISSUE THREAD

**Issue by gaal1le0** [DanBaDo/TheExcuseGenerator#1]
https://github.com/DanBaDo/TheExcuseGenerator/blob/69e4d198a795c56cdc01055c15a4b561c0bad0f7/src/app.js#L26

Cuando vas a hacer un Math.floor debes utilizar la longitud completa de la lista, si no, es imposible que puedas obtener el ultimo elemento del array.

` return list[randomIn(list.length)]; `

**Comment by DanielBanobreDopico** [comment]
La función randomIn(num) retorna un valor aleatorio entre 0 y num.
En la línea señalada espero obteren un índice para un array de JS que tienen índices de enteros consecutivos, correspondiendo el índice 0 al primer elemento. Esto supone que una lista con cuatro elementos use los índices entre 0 y 3.
Si a la función le proporciono como argumento la longitud del array, digamos 4, internamente ejecutara:
* Math.random()*4 que proporcionará un valor decimal entre 0 y 4.
* Math.floor() del valor anterior, que proporcionará un entero entre 0 y 4.
* Proporcionará el entero anterior como salida.

Con lo anterior puedo obtener valores entre 0 y 4 para usar como índice en una array con índices entre 0 y 3. Puedo solucionarlo como en el caso, restando 1 al parámetro de la función, o modificando la función para que reste uno a su salida.

La opción adoptada, sin entrar en las circunstancias en torno a la escritura del código, tiene la ventaja de que la salida de la función resulta semánticamente coherente, facilitando su uso para diferentes utilidades.

**Comment by gaal1le0** [comment]
Perfecto, quería escuchar tu explicación al respecto de porque habías colocado eso.
De hecho, de todas las personas que lo han entregado ninguno ha usado esa solución, por lo que quería saber porque el -1 dentro, pero veo que si sabes el motivo, por lo que me parece correcto.

## Quería asegurarme que sabias que semánticamente era mucho más correcto.

Perdona las molestias

**Comment by gaal1le0** [comment]
## Felicidades!!

Tu reacción ha sido muy buena, a lo largo del bootcamp muchas veces cuestionare tus soluciones solo para escuchar tu explicación y entender tu punto de vista, esto te preparará de cara al lado profesional como programador. Yo diría que es algo muy importante.
